services:
  postgresVideos:
    image: postgres:16
    container_name: postgres_videos
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${VIDEOS_DB_NAME}
      POSTGRES_USER: ${VIDEOS_DB_USER}
      POSTGRES_PASSWORD: ${VIDEOS_DB_PASS}
    volumes:
      - videos_data:/var/lib/postgresql/data
  postgresUser:
    image: postgres:16
    container_name: postgres_user
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASS}
    volumes:
      - users_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - .env

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env

  video_store:
    build:
      context: ./services/video_store 
      dockerfile: Dockerfile
    image: video-streaming-api:latest
    depends_on:
      - postgresVideos
      - kafka 
    ports:
      - "8082:8080"
    restart: unless-stopped
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./services/video_store/observability/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - video_store

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    env_file:
      - .env

  transcoding:
    build:
      context: ./services/transcoding
      dockerfile: Dockerfile
    image: video-streaming-transcoding:latest
    depends_on:
      - kafka
    volumes:
      - C:/Users/Eduardo/Videos/docker_volume_video:/var/videos
    ports:
      - "8081:8080"
    restart: unless-stopped
    env_file:
      - .env

  user_service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    image: video-streaming-user-service:latest
    depends_on:
      - postgresUser
    ports:
      - "8084:8080"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  videos_data:
  users_data: